/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as localHoarderSol from "./localHoarder.sol";
export * as targetContractSol from "./targetContract.sol";
export * as verifierSol from "./verifier.sol";
