/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface LocalHoarderInterface extends utils.Interface {
  functions: {
    "computerToUnsignedGethBlocks(address,uint256)": FunctionFragment;
    "getAllR(uint256)": FunctionFragment;
    "getAllS(uint256)": FunctionFragment;
    "getAllV(uint256)": FunctionFragment;
    "getGethBlocksToBeSend()": FunctionFragment;
    "getProposalTxDataFromGethBlock(uint256)": FunctionFragment;
    "getUnsignedGethBlocks(address)": FunctionFragment;
    "gethBlockNumberToAllSignatures(uint256,uint256)": FunctionFragment;
    "gethBlocksToBeSend(uint256)": FunctionFragment;
    "proposeNewBatch(bytes[],address[],uint256)": FunctionFragment;
    "sendSignature(address,uint8,bytes32,bytes32,uint256)": FunctionFragment;
    "sentGethBlock(uint256)": FunctionFragment;
    "signedComputers(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "computerToUnsignedGethBlocks"
      | "computerToUnsignedGethBlocks(address,uint256)"
      | "getAllR"
      | "getAllR(uint256)"
      | "getAllS"
      | "getAllS(uint256)"
      | "getAllV"
      | "getAllV(uint256)"
      | "getGethBlocksToBeSend"
      | "getGethBlocksToBeSend()"
      | "getProposalTxDataFromGethBlock"
      | "getProposalTxDataFromGethBlock(uint256)"
      | "getUnsignedGethBlocks"
      | "getUnsignedGethBlocks(address)"
      | "gethBlockNumberToAllSignatures"
      | "gethBlockNumberToAllSignatures(uint256,uint256)"
      | "gethBlocksToBeSend"
      | "gethBlocksToBeSend(uint256)"
      | "proposeNewBatch"
      | "proposeNewBatch(bytes[],address[],uint256)"
      | "sendSignature"
      | "sendSignature(address,uint8,bytes32,bytes32,uint256)"
      | "sentGethBlock"
      | "sentGethBlock(uint256)"
      | "signedComputers"
      | "signedComputers(uint256)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "computerToUnsignedGethBlocks",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "computerToUnsignedGethBlocks(address,uint256)",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllR",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllR(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllS",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllS(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllV",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllV(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getGethBlocksToBeSend",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGethBlocksToBeSend()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalTxDataFromGethBlock",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalTxDataFromGethBlock(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnsignedGethBlocks",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnsignedGethBlocks(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "gethBlockNumberToAllSignatures",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "gethBlockNumberToAllSignatures(uint256,uint256)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "gethBlocksToBeSend",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "gethBlocksToBeSend(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeNewBatch",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeNewBatch(bytes[],address[],uint256)",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sendSignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sendSignature(address,uint8,bytes32,bytes32,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sentGethBlock",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "sentGethBlock(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "signedComputers",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "signedComputers(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "computerToUnsignedGethBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computerToUnsignedGethBlocks(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAllR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllR(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAllS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllS(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAllV", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllV(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGethBlocksToBeSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGethBlocksToBeSend()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalTxDataFromGethBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalTxDataFromGethBlock(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnsignedGethBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnsignedGethBlocks(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gethBlockNumberToAllSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gethBlockNumberToAllSignatures(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gethBlocksToBeSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gethBlocksToBeSend(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeNewBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeNewBatch(bytes[],address[],uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendSignature(address,uint8,bytes32,bytes32,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sentGethBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sentGethBlock(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signedComputers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signedComputers(uint256)",
    data: BytesLike
  ): Result;

  events: {
    "allSignatureReceived(uint256)": EventFragment;
    "proposeNewBatchEvent(bytes,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "allSignatureReceived"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "allSignatureReceived(uint256)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "proposeNewBatchEvent"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "proposeNewBatchEvent(bytes,uint256)"
  ): EventFragment;
}

export interface allSignatureReceivedEventObject {
  gethBlockNumber: BigNumber;
}
export type allSignatureReceivedEvent = TypedEvent<
  [BigNumber],
  allSignatureReceivedEventObject
>;

export type allSignatureReceivedEventFilter =
  TypedEventFilter<allSignatureReceivedEvent>;

export interface proposeNewBatchEventEventObject {
  txData: string;
  gethBlockNumber: BigNumber;
}
export type proposeNewBatchEventEvent = TypedEvent<
  [string, BigNumber],
  proposeNewBatchEventEventObject
>;

export type proposeNewBatchEventEventFilter =
  TypedEventFilter<proposeNewBatchEventEvent>;

export interface LocalHoarder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LocalHoarderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    computerToUnsignedGethBlocks(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "computerToUnsignedGethBlocks(address,uint256)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAllR(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    "getAllR(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getAllS(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    "getAllS(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getAllV(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number[]]>;

    "getAllV(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number[]]>;

    getGethBlocksToBeSend(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    "getGethBlocksToBeSend()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getProposalTxDataFromGethBlock(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getProposalTxDataFromGethBlock(uint256)"(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getUnsignedGethBlocks(
      computer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    "getUnsignedGethBlocks(address)"(
      computer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    gethBlockNumberToAllSignatures(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number, string, string] & { v: number; r: string; s: string }>;

    "gethBlockNumberToAllSignatures(uint256,uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number, string, string] & { v: number; r: string; s: string }>;

    gethBlocksToBeSend(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "gethBlocksToBeSend(uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    proposeNewBatch(
      txDataBatch: PromiseOrValue<BytesLike>[],
      targetContractAddresses: PromiseOrValue<string>[],
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "proposeNewBatch(bytes[],address[],uint256)"(
      txDataBatch: PromiseOrValue<BytesLike>[],
      targetContractAddresses: PromiseOrValue<string>[],
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendSignature(
      computer: PromiseOrValue<string>,
      _v: PromiseOrValue<BigNumberish>,
      _r: PromiseOrValue<BytesLike>,
      _s: PromiseOrValue<BytesLike>,
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "sendSignature(address,uint8,bytes32,bytes32,uint256)"(
      computer: PromiseOrValue<string>,
      _v: PromiseOrValue<BigNumberish>,
      _r: PromiseOrValue<BytesLike>,
      _s: PromiseOrValue<BytesLike>,
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sentGethBlock(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "sentGethBlock(uint256)"(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    signedComputers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "signedComputers(uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  computerToUnsignedGethBlocks(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "computerToUnsignedGethBlocks(address,uint256)"(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAllR(
    gethBlockNumber: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "getAllR(uint256)"(
    gethBlockNumber: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getAllS(
    gethBlockNumber: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "getAllS(uint256)"(
    gethBlockNumber: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getAllV(
    gethBlockNumber: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number[]>;

  "getAllV(uint256)"(
    gethBlockNumber: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number[]>;

  getGethBlocksToBeSend(overrides?: CallOverrides): Promise<BigNumber[]>;

  "getGethBlocksToBeSend()"(overrides?: CallOverrides): Promise<BigNumber[]>;

  getProposalTxDataFromGethBlock(
    gethBlock: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  "getProposalTxDataFromGethBlock(uint256)"(
    gethBlock: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getUnsignedGethBlocks(
    computer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  "getUnsignedGethBlocks(address)"(
    computer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  gethBlockNumberToAllSignatures(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[number, string, string] & { v: number; r: string; s: string }>;

  "gethBlockNumberToAllSignatures(uint256,uint256)"(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[number, string, string] & { v: number; r: string; s: string }>;

  gethBlocksToBeSend(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "gethBlocksToBeSend(uint256)"(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  proposeNewBatch(
    txDataBatch: PromiseOrValue<BytesLike>[],
    targetContractAddresses: PromiseOrValue<string>[],
    gethBlockNumber: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "proposeNewBatch(bytes[],address[],uint256)"(
    txDataBatch: PromiseOrValue<BytesLike>[],
    targetContractAddresses: PromiseOrValue<string>[],
    gethBlockNumber: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendSignature(
    computer: PromiseOrValue<string>,
    _v: PromiseOrValue<BigNumberish>,
    _r: PromiseOrValue<BytesLike>,
    _s: PromiseOrValue<BytesLike>,
    gethBlockNumber: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "sendSignature(address,uint8,bytes32,bytes32,uint256)"(
    computer: PromiseOrValue<string>,
    _v: PromiseOrValue<BigNumberish>,
    _r: PromiseOrValue<BytesLike>,
    _s: PromiseOrValue<BytesLike>,
    gethBlockNumber: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sentGethBlock(
    gethBlock: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "sentGethBlock(uint256)"(
    gethBlock: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  signedComputers(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  "signedComputers(uint256)"(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    computerToUnsignedGethBlocks(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "computerToUnsignedGethBlocks(address,uint256)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllR(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "getAllR(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getAllS(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "getAllS(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getAllV(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number[]>;

    "getAllV(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number[]>;

    getGethBlocksToBeSend(overrides?: CallOverrides): Promise<BigNumber[]>;

    "getGethBlocksToBeSend()"(overrides?: CallOverrides): Promise<BigNumber[]>;

    getProposalTxDataFromGethBlock(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    "getProposalTxDataFromGethBlock(uint256)"(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getUnsignedGethBlocks(
      computer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "getUnsignedGethBlocks(address)"(
      computer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    gethBlockNumberToAllSignatures(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number, string, string] & { v: number; r: string; s: string }>;

    "gethBlockNumberToAllSignatures(uint256,uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number, string, string] & { v: number; r: string; s: string }>;

    gethBlocksToBeSend(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "gethBlocksToBeSend(uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposeNewBatch(
      txDataBatch: PromiseOrValue<BytesLike>[],
      targetContractAddresses: PromiseOrValue<string>[],
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    "proposeNewBatch(bytes[],address[],uint256)"(
      txDataBatch: PromiseOrValue<BytesLike>[],
      targetContractAddresses: PromiseOrValue<string>[],
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    sendSignature(
      computer: PromiseOrValue<string>,
      _v: PromiseOrValue<BigNumberish>,
      _r: PromiseOrValue<BytesLike>,
      _s: PromiseOrValue<BytesLike>,
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    "sendSignature(address,uint8,bytes32,bytes32,uint256)"(
      computer: PromiseOrValue<string>,
      _v: PromiseOrValue<BigNumberish>,
      _r: PromiseOrValue<BytesLike>,
      _s: PromiseOrValue<BytesLike>,
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    sentGethBlock(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "sentGethBlock(uint256)"(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    signedComputers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    "signedComputers(uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "allSignatureReceived(uint256)"(
      gethBlockNumber?: null
    ): allSignatureReceivedEventFilter;
    allSignatureReceived(
      gethBlockNumber?: null
    ): allSignatureReceivedEventFilter;

    "proposeNewBatchEvent(bytes,uint256)"(
      txData?: null,
      gethBlockNumber?: null
    ): proposeNewBatchEventEventFilter;
    proposeNewBatchEvent(
      txData?: null,
      gethBlockNumber?: null
    ): proposeNewBatchEventEventFilter;
  };

  estimateGas: {
    computerToUnsignedGethBlocks(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "computerToUnsignedGethBlocks(address,uint256)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllR(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAllR(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllS(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAllS(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllV(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAllV(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGethBlocksToBeSend(overrides?: CallOverrides): Promise<BigNumber>;

    "getGethBlocksToBeSend()"(overrides?: CallOverrides): Promise<BigNumber>;

    getProposalTxDataFromGethBlock(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getProposalTxDataFromGethBlock(uint256)"(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUnsignedGethBlocks(
      computer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getUnsignedGethBlocks(address)"(
      computer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gethBlockNumberToAllSignatures(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "gethBlockNumberToAllSignatures(uint256,uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gethBlocksToBeSend(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "gethBlocksToBeSend(uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposeNewBatch(
      txDataBatch: PromiseOrValue<BytesLike>[],
      targetContractAddresses: PromiseOrValue<string>[],
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "proposeNewBatch(bytes[],address[],uint256)"(
      txDataBatch: PromiseOrValue<BytesLike>[],
      targetContractAddresses: PromiseOrValue<string>[],
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendSignature(
      computer: PromiseOrValue<string>,
      _v: PromiseOrValue<BigNumberish>,
      _r: PromiseOrValue<BytesLike>,
      _s: PromiseOrValue<BytesLike>,
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "sendSignature(address,uint8,bytes32,bytes32,uint256)"(
      computer: PromiseOrValue<string>,
      _v: PromiseOrValue<BigNumberish>,
      _r: PromiseOrValue<BytesLike>,
      _s: PromiseOrValue<BytesLike>,
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sentGethBlock(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "sentGethBlock(uint256)"(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    signedComputers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "signedComputers(uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    computerToUnsignedGethBlocks(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "computerToUnsignedGethBlocks(address,uint256)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllR(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAllR(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllS(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAllS(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllV(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAllV(uint256)"(
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGethBlocksToBeSend(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGethBlocksToBeSend()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProposalTxDataFromGethBlock(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getProposalTxDataFromGethBlock(uint256)"(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUnsignedGethBlocks(
      computer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getUnsignedGethBlocks(address)"(
      computer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gethBlockNumberToAllSignatures(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "gethBlockNumberToAllSignatures(uint256,uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gethBlocksToBeSend(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "gethBlocksToBeSend(uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposeNewBatch(
      txDataBatch: PromiseOrValue<BytesLike>[],
      targetContractAddresses: PromiseOrValue<string>[],
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "proposeNewBatch(bytes[],address[],uint256)"(
      txDataBatch: PromiseOrValue<BytesLike>[],
      targetContractAddresses: PromiseOrValue<string>[],
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendSignature(
      computer: PromiseOrValue<string>,
      _v: PromiseOrValue<BigNumberish>,
      _r: PromiseOrValue<BytesLike>,
      _s: PromiseOrValue<BytesLike>,
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "sendSignature(address,uint8,bytes32,bytes32,uint256)"(
      computer: PromiseOrValue<string>,
      _v: PromiseOrValue<BigNumberish>,
      _r: PromiseOrValue<BytesLike>,
      _s: PromiseOrValue<BytesLike>,
      gethBlockNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sentGethBlock(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "sentGethBlock(uint256)"(
      gethBlock: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    signedComputers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "signedComputers(uint256)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
