/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as localHoarderSol from "./localHoarder.sol";
export type { localHoarderSol };
import type * as targetContractSol from "./targetContract.sol";
export type { targetContractSol };
import type * as verifierSol from "./verifier.sol";
export type { verifierSol };
export * as factories from "./factories";
export type { LocalHoarder } from "./localHoarder.sol/LocalHoarder";
export { LocalHoarder__factory } from "./factories/localHoarder.sol/LocalHoarder__factory";
export type { TargetContract } from "./targetContract.sol/TargetContract";
export { TargetContract__factory } from "./factories/targetContract.sol/TargetContract__factory";
export type { Verifier } from "./verifier.sol/Verifier";
export { Verifier__factory } from "./factories/verifier.sol/Verifier__factory";
